name: Test and Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Deno
              uses: denoland/setup-deno@v1
              with:
                  deno-version: v1.x

            - name: Check formatting
              run: deno fmt --check

            - name: Run linter
              run: deno lint

            - name: Run Deno tests
              run: deno test --allow-net

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install Node.js dependencies
              run: npm install

            - name: Build for Node.js
              run: npm run build

            - name: Run Node.js tests
              run: node --test dist/tests/
