name: Test and Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Deno
              uses: denoland/setup-deno@v1
              with:
                  deno-version: v1.x

            - name: Check formatting
              run: deno fmt --check

            - name: Run linter
              run: deno lint

            - name: Run Deno tests
              run: deno test --allow-net